name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ published ]
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  CL: /source-charset:.949 /execution-charset:.949
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - working-directory: ${{env.GITHUB_WORKSPACE}}
        run: >-
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} 
          ${{env.SOLUTION_FILE_PATH}}
      - run: echo "filename=${GITHUB_REPOSITORY#*/}-${GITHUB_REF##*/}.zip" >> $GITHUB_OUTPUT
        shell: bash
        id: zip
      - uses: vimtor/action-zip@v1.2
        with:
          files: Release/comm.drv16 Release/display.drv16 Release/gdi.exe16 Release/keyboard.drv16 Release/krnl386.exe16 Release/libwine.dll Release/mmsystem.dll16 Release/mouse.drv16 Release/san5pk-64.exe Release/sound.drv16 Release/system.drv16 Release/timer.drv16 Release/toolhelp.dll16 Release/user.exe16 Release/vm86.dll Release/wing.dll16
          dest: ${{steps.zip.outputs.filename}}
      - uses: actions/upload-artifact@v4
        with:
          path: ${{steps.zip.outputs.filename}}
    outputs:
      filename: ${{steps.zip.outputs.filename}}
  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: tubone24/update_release@v1.3.1
        id: update_release
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          upload_url: ${{steps.update_release.outputs.upload_url}}
          asset_path: artifact/${{needs.build.outputs.filename}}
          asset_name: ${{needs.build.outputs.filename}}
          asset_content_type: application/zip
